// ─────────────────────────────────────────────────
// @kannan19302/ui — UniERP Design Language 1.0 ("Meridian Instrument")
// Unified Public Root Barrel Export
// ─────────────────────────────────────────────────

export * from "./primitives";
export * from "./inputs";
export * from "./overlays";
export * from "./navigation";
export * from "./data-display";
export * from "./data-grid";
export * from "./forms";
export * from "./layout";
export * from "./shell";
export * from "./studio";
export * from "./dashboard";
export * from "./charts";
export * from "./theme";
export * from "./blocks";
export * from "./brand";

// Explicit non-conflicting exports from workflow, form-engine, notifications
export {
  ApprovalChain,
  type Approver,
  type ApprovalStatus,
  type ApprovalChainProps,
  LifecycleTracker,
  type LifecycleStage,
  type LifecycleTrackerProps,
  StageProgressionBar,
  type StageProgressionBarProps,
  type StageItem,
  type StageStatus,
  type StageDensity,
  PeriodCloseCockpit,
  type PeriodCloseCockpitProps,
  type CloseTask,
  type CloseTaskStatus,
  type CockpitDensity,
  ActivityWorkLogStream,
  type ActivityWorkLogStreamProps,
  type WorkLogEntry,
  type WorkLogEntryType,
  AllocationRuleBuilder,
  type AllocationRuleBuilderProps,
  type AllocationTarget,
  type AllocationBasisType,
  TopologyDependencyGraph,
  type TopologyDependencyGraphProps,
  type TopologyNode,
  type TopologyEdge,
  type TopologyNodeType,
  type TopologyHealth,
  IncidentEscalationTree,
  type IncidentEscalationTreeProps,
  type EscalationTier,
  type EscalationResponder,
  type NotificationChannelType,
  type ResponderStatus,
  type TierEscalationStatus,
  PaymentRunCockpit,
  type PaymentRunCockpitProps,
  type PayableInvoice,
  type PaymentRail,
  ComplianceEvidenceCollector,
  type ComplianceEvidenceCollectorProps,
  type ComplianceControlItem,
  type ComplianceEvidenceItem,
  type ControlTestStatus,
  type EvidenceReviewState,
  WarehousePickPackWaveConsole,
  type WarehousePickPackWaveConsoleProps,
  type PickTask,
  type ToteSlot,
  BankRuleConditionBuilder,
  type BankRuleConditionBuilderProps,
  type BankRule,
  type RuleCondition,
  type RuleField,
  type RuleOperator,
  CanaryRolloutProgressVisualizer,
  type CanaryRolloutProgressVisualizerProps,
  type CanaryMetricComparison,
  type CanaryStatus,
  ClinicalOrderEntryPad,
  type ClinicalOrderEntryPadProps,
  type StagedClinicalOrder,
  type PatientBannerInfo,
  type OrderCategory,
  type OrderPriority,
  ExpensePolicyRuleAuditor,
  type ExpensePolicyRuleAuditorProps,
  type ExpenseTransactionAuditItem,
  type PolicyRuleAuditCheck,
  type PolicyViolationSeverity,

  KubernetesPodConsole,
  type KubernetesPodConsoleProps,
  type PodLogEntry,
  type PodLifecycleStatus,
  SupplierTaxComplianceVerifier,
  type SupplierTaxComplianceVerifierProps,
  type SupplierTaxProfile,
  type TaxValidationStatus,
  type TaxDocumentCertificate,
  MassPayoutBatchApprover,
  type MassPayoutBatchApproverProps,
  type PayoutBatchLine,
  type PaymentRailType,
  type SanctionScreeningStatus,
  RfiSubmissionWorkflow,
  type RfiSubmissionWorkflowProps,
  type RfiAttachment,
  type RfiActivityLogItem,
  DataPipelineDagVisualizer,
  type DataPipelineDagVisualizerProps,
  type DagTaskNode,
  type DagTaskStatus,
  ClinicalDecisionSupportAlert,
  type ClinicalDecisionSupportAlertProps,
  type CdsPatientInfo,
  type CdsAlternativeRecommendation,
  type CdsSeverity,
  FeatureFlagTargetingRuleBuilder,
  type FeatureFlagTargetingRuleBuilderProps,
  type TargetingRule,
  type RuleClause,
  type FlagVariation,
  ServiceCatalogCartCheckout,
  type ServiceCatalogCartCheckoutProps,
  type ServiceCartItem,
  type ServiceItemCategory,
  type BillingFrequency,
  OnCallRotationScheduleCalendar,
  type OnCallRotationScheduleCalendarProps,
  type OnCallShift,
  type EscalationLayer,
  BillableTimeStopwatchDock,
  type BillableMatterOption,
  type BillableTimeStopwatchDockProps,
  CashSweepLiquidityOptimizer,
  type SweepDirection,
  type TreasuryAccountNode,
  type CashSweepLiquidityOptimizerProps,
  ClinicalTrialCohortRandomizer,
  type BlindingMode,
  type ClinicalStudyProtocol,
  type ClinicalTrialCohortRandomizerProps,
  DsarRequestLifecycleManager,
  type DsarStage,
  type DsarRequestType,
  type DsarSystemDataNode,
  type DsarCaseDetails,
  type DsarRequestLifecycleManagerProps,
  AlertRuleConditionBuilder,
  type AlertRuleConditionBuilderProps,
  type AlertRuleModel,
  type AlertSeverity,
  type AlertOperator,
  TaxWithholdingComplianceCockpit,
  type TaxWithholdingComplianceCockpitProps,
  type VendorTaxProfile,
  type TinMatchStatus,
  type TaxFormType,
  type WithholdingStatus,
  ConstructionSubmittalRegister,
  type ConstructionSubmittalRegisterProps,
  type ConstructionSubmittalItem,
  type ConstructionSubmittalStatus,
  LegalHoldCustodianTracker,
  type LegalHoldCustodianTrackerProps,
  type LegalMatterInfo,
  type LegalHoldCustodian,
  type LegalHoldStatus,
  SecurityWafRuleInspector,
  type SecurityWafRuleInspectorProps,
  type WafSecurityEventItem,
  type WafActionTaken,
  type ThreatCategory,
  ClinicalEdcFieldVerifier,
  type ClinicalEdcFieldVerifierProps,
  type EdcFieldRecord,
  type EdcSdvStatus,
  ContractClauseRiskAnalyzer,
  type ContractClauseRiskAnalyzerProps,
  type ContractClauseRiskItem,
  type ClauseRiskSeverity,
  type ClauseResolutionStatus,
  CustomerSlaBreachTimeline,
  type CustomerSlaBreachTimelineProps,
  type CustomerSlaTicket,
  type SlaSeverityLevel,
  type SlaBreachStatus,
} from "./workflow";






export {
  SettingsPage,
  type SettingsPageProps,
  type SettingSchemaEntry,
  type SettingScope,
  type SettingType,
  SchemaForm,
  type SchemaFormProps,
  type FormFieldSchema,
  type FormSectionSchema,
  type FormFieldType,
} from "./form-engine";

export {
  DemoBanner,
  type DemoBannerProps,
  NotificationCenter,
  type NotificationCenterProps,
  type NotificationItem,
  type NotificationPriority,
  type NotificationCategory,
} from "./notifications";
